CREATE TABLE CARRERA(
    IDCARRERA     NUMBER PRIMARY KEY,
    NOMBRE        VARCHAR2(40)
);

CREATE SEQUENCE SQ_CARRERA
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;


CREATE TABLE CURSO(
    IDCURSO     NUMBER PRIMARY KEY,
    NOMBRE        VARCHAR2(50)
);

CREATE SEQUENCE SQ_CURSO
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;


CREATE TABLE ESTUDIANTE(
    IDESTUDIANTE        NUMBER PRIMARY KEY,
    CODIGO              NUMBER,
    NOMBRE_COMPLETO     VARCHAR2(50),
    CORREO              VARCHAR2(50)
);

CREATE SEQUENCE SQ_ESTUDIANTE
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

INSERT INTO CARRERA VALUES (
    SQ_CARRERA.NEXTVAL,
    'ING. SISTEMAS'
);

INSERT INTO CARRERA VALUES (
    SQ_CARRERA.NEXTVAL,
    'MEDICINA'
);

INSERT INTO CARRERA VALUES (
    SQ_CARRERA.NEXTVAL,
    'ING. AMBIENTAL'
);

INSERT INTO CARRERA VALUES (
    SQ_CARRERA.NEXTVAL,
    'ING. CIVIL'
);

INSERT INTO CARRERA VALUES (
    SQ_CARRERA.NEXTVAL,
    'ING. INFORMATICA'
);

INSERT INTO CARRERA VALUES (
    SQ_CARRERA.NEXTVAL,
    'ING. SOFTWARE'
);

INSERT INTO CARRERA VALUES (
    SQ_CARRERA.NEXTVAL,
    'MECATRONICA'
);

commit;

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Diseño de Bases de Datos'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Investigación Operativa 2'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Estructuras discretas'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Algoritmos y Estruc. de Datos'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Big Data'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Arquitectura de Software'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Sistemas Digitales'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Microprocesadores'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'LP 2'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Matematica 4'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Microeconomia'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'TGS'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Filosofia'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Matematica'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'LP 1'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'SAP'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Macroeconomia'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Dinamica de Sistemas'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Microprocesadores'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Analisis y Diseño de Sistemas'
);

INSERT INTO CURSO VALUES (
    SQ_CURSO.NEXTVAL,
    'Simulación de Sistemas'
);

commit;

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    2016200001,
    'ABARCA VERA GERSON DAVID',
    'geda.abarca@hotmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1823010670,
    'AMANQUI CHAVEZ RIVALDO JULIO',
    'rjulio2800@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1913010953,
    'BERRIO HUAMANI MIGUEL ANGEL',
    'miguelberrioh@hotmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    2014100492,
    'CASTILLON CARDENAS JAIRO DANTE',
    'jairo.2.26.m@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1823010257,
    'CCALLOQUISPE QUISPE ANGEL ANDERSON',
    'zelsperson@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1823110215,
    'GAMBOA CONDORI CRISTIAN',
    'cristian9gc@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    2014200776,
    'GOMEZ TORRES JASON FIDEL',
    'jasongomez246@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1913010909,
    'GONZALES GOMEZ DYLAN CARUSSO',
    'dylancartroll@hotmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1913010940,
    'GONZALES MOYA LUIGGI PAOLO',
    'luiggi.gonzalesmoya@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    2015200357,
    'GUZMAN DAVILA DIANA AZUCENA',
    'dianagzmn.05@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    2016100125,
    'HOYOS REYNA JORGE ARMANDO',
    'thelordjorge@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1823010636,
    'RUIZ FLORES PEDRO PABLO',
    'pedropablo1407@hotmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1823010111,
    'INGA MOLINA SEBASTIAN LUIS',
    'ingaamable@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    2017110647,
    'PUMA CCALLO JOHN CHRISTOFER',
    'john_puma_24@outlook.es'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    2013200084,
    'VEJARANO CERNA AXL JAIME JAVIER',
    'axlvejarano@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1823110517,
    'VERA YAURI VICTOR ADRIAN',
    'victorverayauri@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    2014200177,
    'VILLA UÑAPILLCO TITO DARWIN',
    'styf.15.dota@gmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1813011387,
    'YACHACHIN YACOLCA DIANA LUCIA',
    'dianaluciaya@hotmail.com'
);

INSERT INTO ESTUDIANTE VALUES (
    SQ_ESTUDIANTE.NEXTVAL,
    1913110201,
    'ZAPATA YAMO LUIS JHONAYQUER',
    'jhonayquer@gmail.com'
);

commit;


CREATE TABLE ESTUDIANTE_CURSO(
    IDEC              NUMBER PRIMARY KEY,
    IDCARRERA         NUMBER REFERENCES CARRERA,
    IDCURSO           NUMBER REFERENCES CURSO,
    IDESTUDIANTE      NUMBER REFERENCES ESTUDIANTE
);

CREATE SEQUENCE SQ_ESTUDIANTECURSO
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;


INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    1,
    1
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    2,
    1
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    3,
    1
);

commit;

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    4,
    2
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    1,
    2
);

commit;

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    5,
    3
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    6,
    3
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    1,
    3
);

commit;

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    9,
    4
);

commit;

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    10,
    5
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    7,
    5
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    3,
    5
);

commit;

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    5,
    7,
    6
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    5,
    1,
    6
);

commit;

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    15,
    7
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    1,
    7
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    10,
    7
);

commit;

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    4,
    8
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    20,
    8
);

commit;

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    10,
    9
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    1,
    9
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    17,
    9
);

commit;

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    4,
    1,
    10
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    4,
    7,
    10
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    4,
    8,
    10
);

commit;

------------------------------

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    3,
    19,
    11
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    3,
    20,
    11
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    3,
    21,
    11
);

commit;

----------------------

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    6,
    1,
    12
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    6,
    14,
    12
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    6,
    8,
    12
);

commit;

------------------

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    11,
    13
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    15,
    13
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    1,
    16,
    13
);

commit;

--------------------

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    2,
    17,
    14
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    2,
    4,
    14
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    2,
    20,
    14
);

commit;

----------------------

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    4,
    1,
    15
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    4,
    12,
    15
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    4,
    7,
    15
);

commit;

--------------------

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    7,
    18,
    16
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    7,
    13,
    16
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    7,
    14,
    16
);

commit;

------------------

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    2,
    11,
    17
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    2,
    16,
    17
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    2,
    13,
    17
);

commit;

-----------------------

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    5,
    1,
    18
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    5,
    12,
    18
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    5,
    7,
    18
);

commit;

---------------

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    6,
    15,
    19
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    6,
    17,
    19
);

INSERT INTO ESTUDIANTE_CURSO VALUES (
    SQ_ESTUDIANTECURSO.NEXTVAL,
    6,
    19,
    19
);

commit;

SELECT *
FROM ESTUDIANTE_CURSO;

------------------

SELECT
    E.IDEC,
    R.NOMBRE CARRERA,
    S.NOMBRE CURSO,
    T.NOMBRE_COMPLETO ESTUDIANTE,
    T.CODIGO ESTUDIANTE
FROM
    CARRERA R,
    CURSO S,
    ESTUDIANTE T,
    ESTUDIANTE_CURSO E
WHERE
    R.IDCARRERA = E.IDCARRERA AND
    S.IDCURSO = E.IDCURSO AND
    T.IDESTUDIANTE = E.IDESTUDIANTE 
ORDER BY E.IDEC;



